version: '3.1'
services:
  fire-spread-database:
      container_name: fire-spread-database
      image: postgres:alpine
      restart: always
      environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_DB}
      ports:
        - ${POSTGRES_PORT}:5432
      volumes:
        - ./.docker/database:/var/lib/postgresql/data